"""create table transaction

Revision ID: 6b61e689098e
Revises: 9925adbe0c25
Create Date: 2018-08-25 15:29:44.926016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b61e689098e'
down_revision = '9925adbe0c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('upgrade_id', sa.Integer(), nullable=True),
    sa.Column('balchange', sa.Float(), nullable=True),
    sa.Column('newbal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['upgrade_id'], ['upgrade.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_timestamp'), 'transaction', ['timestamp'], unique=False)
    op.add_column('purchase', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_index('ix_purchase_timestamp', table_name='purchase')
    op.drop_column('purchase', 'timestamp')
    op.drop_index('ix_upgrade_timestamp', table_name='upgrade')
    op.drop_column('upgrade', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_upgrade_timestamp', 'upgrade', ['timestamp'], unique=False)
    op.add_column('purchase', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_purchase_timestamp', 'purchase', ['timestamp'], unique=False)
    op.drop_column('purchase', 'amount')
    op.drop_index(op.f('ix_transaction_timestamp'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
